{
  "cards": [
    {
      "key": 1,
      "name": "Lil FreeB",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 0,
      "rcost": 0,
      "att": 1,
      "def": 1,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 0,
      "multiplier": 1,
      "total_value": "",
      "string": "000100011300000C"
    },
    {
      "key": 2,
      "name": "Lil FreeC",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 0,
      "rcost": 0,
      "att": 0,
      "def": 2,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 0,
      "multiplier": 1,
      "total_value": "",
      "string": "000200002300000C"
    },
    {
      "key": 3,
      "name": "Lil Rounded",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 1,
      "rcost": 0,
      "att": 1,
      "def": 1,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 1,
      "multiplier": 1,
      "total_value": "",
      "string": "0003010113E0000C"
    },
    {
      "key": 4,
      "name": "Lil Aggro",
      "type": "Machine",
      "description": "",
      "trait1": "Charge",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 1,
      "rcost": 0,
      "att": 1,
      "def": 1,
      "str_type": 3,
      "str_trait1": 4,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 1,
      "multiplier": 1,
      "total_value": "",
      "string": "000401011340000C"
    },
    {
      "key": 5,
      "name": "Lil Survivor",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 1,
      "rcost": 0,
      "att": 1,
      "def": 2,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 1,
      "multiplier": 1,
      "total_value": "",
      "string": "000501012300000C"
    },
    {
      "key": 6,
      "name": "Lil Punchy",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 1,
      "rcost": 0,
      "att": 2,
      "def": 1,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 1,
      "multiplier": 1,
      "total_value": "",
      "string": "000601021300000C"
    },
    {
      "key": 7,
      "name": "Lil Taunt",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 1,
      "rcost": 0,
      "att": 1,
      "def": 2,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "R",
      "total_cost": 1,
      "multiplier": 1,
      "total_value": "",
      "string": "0007010123E0000R"
    },
    {
      "key": 8,
      "name": "Lil Blocky",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 1,
      "rcost": 0,
      "att": 0,
      "def": 3,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 1,
      "multiplier": 1,
      "total_value": "",
      "string": "000801003300000C"
    },
    {
      "key": 9,
      "name": "Lil Vamp",
      "type": "Machine",
      "description": "",
      "trait1": "Lifesteal",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 1,
      "rcost": 0,
      "att": 1,
      "def": 1,
      "str_type": 3,
      "str_trait1": "B",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "R",
      "total_cost": 1,
      "multiplier": 1,
      "total_value": "",
      "string": "0009010113B0000R"
    },
    {
      "key": 10,
      "name": "Kicksy",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 4,
      "def": 1,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "001002041300000C"
    },
    {
      "key": 11,
      "name": "Punchy",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 3,
      "def": 2,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "001102032300000C"
    },
    {
      "key": 12,
      "name": "Rounded",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 2,
      "def": 3,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "001202023300000C"
    },
    {
      "key": 13,
      "name": "Survivor",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 1,
      "def": 4,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "001302014300000C"
    },
    {
      "key": 14,
      "name": "Aggro",
      "type": "Machine",
      "description": "",
      "trait1": "Charge",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 2,
      "def": 1,
      "str_type": 3,
      "str_trait1": 4,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "R",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "001402021340000R"
    },
    {
      "key": 15,
      "name": "Taunt",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 1,
      "def": 3,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "0015020133E0000C"
    },
    {
      "key": 16,
      "name": "Aggro Taunt",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 2,
      "def": 2,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "0016020223E0000C"
    },
    {
      "key": 17,
      "name": "Vamp",
      "type": "Machine",
      "description": "",
      "trait1": "Lifesteal",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 2,
      "def": 2,
      "str_type": 3,
      "str_trait1": "B",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "0017020223B0000C"
    },
    {
      "key": 18,
      "name": "Drawer",
      "type": "Machine",
      "description": "Draw 1",
      "trait1": "Battlecry",
      "trait2": "Draw",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 2,
      "def": 1,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": 9,
      "str_trait3": 0,
      "str_desc": 14,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "001802021319014C"
    },
    {
      "key": 19,
      "name": "Recruits",
      "type": "Machine",
      "description": "Recruit 1 Machine with < 1 attack",
      "trait1": "Battlecry",
      "trait2": "Recruit",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 2,
      "def": 1,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "C",
      "str_trait3": 0,
      "str_desc": "3F",
      "rarity": "R",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "00190202131C03FR"
    },
    {
      "key": 20,
      "name": "Puller",
      "type": "Machine",
      "description": "Draw 1 Machine from deck with < 2 mcost",
      "trait1": "Battlecry",
      "trait2": "Draw",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 3,
      "def": 1,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": 9,
      "str_trait3": 0,
      "str_desc": 16,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "002002031319016C"
    },
    {
      "key": 21,
      "name": "Rattlerdraw",
      "type": "Machine",
      "description": "Draw 1",
      "trait1": "Deathrattle",
      "trait2": "Draw",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 2,
      "def": 2,
      "str_type": 3,
      "str_trait1": 6,
      "str_trait2": 9,
      "str_trait3": 0,
      "str_desc": 14,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "002102022369014C"
    },
    {
      "key": 22,
      "name": "Rattlerecruit",
      "type": "Machine",
      "description": "Deal 1 Damage to 1 random target",
      "trait1": "Deathrattle",
      "trait2": "Damage",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 2,
      "def": 2,
      "str_type": 3,
      "str_trait1": 6,
      "str_trait2": 5,
      "str_trait3": 0,
      "str_desc": 4,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "002202022365004C"
    },
    {
      "key": 23,
      "name": "CryHealer",
      "type": "Machine",
      "description": "Heal 2",
      "trait1": "Battlecry",
      "trait2": "Heal",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 2,
      "def": 2,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "A",
      "str_trait3": 0,
      "str_desc": 36,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "00230202231A036C"
    },
    {
      "key": 24,
      "name": "DeathrattleHeal",
      "type": "Machine",
      "description": "Heal 1 random Machine",
      "trait1": "Deathrattle",
      "trait2": "Heal",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 2,
      "def": 2,
      "str_type": 3,
      "str_trait1": 6,
      "str_trait2": "A",
      "str_trait3": 0,
      "str_desc": 36,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "00240202236A036C"
    },
    {
      "key": 25,
      "name": "Mid Puller",
      "type": "Machine",
      "description": "Draw 1 Machine from deck with < 3 mcost",
      "trait1": "Battlecry",
      "trait2": "Draw",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 3,
      "def": 2,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": 9,
      "str_trait3": 0,
      "str_desc": 17,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "002503032319017C"
    },
    {
      "key": 26,
      "name": "Mid Kicksy",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 4,
      "def": 2,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "002603042300000C"
    },
    {
      "key": 27,
      "name": "Mid Punchy",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 4,
      "def": 3,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "002703043300000C"
    },
    {
      "key": 28,
      "name": "Mid Rounded",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 3,
      "def": 3,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "002803033300000C"
    },
    {
      "key": 29,
      "name": "Mid Survivor",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 2,
      "def": 5,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "002903025300000C"
    },
    {
      "key": 30,
      "name": "Mid Aggro",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 1,
      "def": 6,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "003003016300000C"
    },
    {
      "key": 31,
      "name": "Mid Taunt",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 0,
      "def": 7,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "003103007300000C"
    },
    {
      "key": 32,
      "name": "Aggro Taunt L",
      "type": "Machine",
      "description": "",
      "trait1": "Lifesteal",
      "trait2": "Charge",
      "trait3": "",
      "typenum": 1,
      "lcost": 1,
      "mcost": 1,
      "rcost": 0,
      "att": 4,
      "def": 2,
      "str_type": 3,
      "str_trait1": "B",
      "str_trait2": 4,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "L",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "0032110423B4000L"
    },
    {
      "key": 33,
      "name": "Mid Vamp L",
      "type": "Machine",
      "description": "",
      "trait1": "Charge",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 1,
      "mcost": 1,
      "rcost": 0,
      "att": 4,
      "def": 2,
      "str_type": 3,
      "str_trait1": 4,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "E",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "003311042340000E"
    },
    {
      "key": 34,
      "name": "CryHealer L",
      "type": "Machine",
      "description": "Heal 2",
      "trait1": "Battlecry",
      "trait2": "Heal",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 1,
      "rcost": 1,
      "att": 2,
      "def": 4,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "A",
      "str_trait3": 0,
      "str_desc": 36,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "00340112431A036C"
    },
    {
      "key": 35,
      "name": "CryBuffer",
      "type": "Machine",
      "description": "Give 1 Machine +1/+0 until Turn end",
      "trait1": "Battlecry",
      "trait2": "Buff",
      "trait3": "",
      "typenum": 1,
      "lcost": 1,
      "mcost": 1,
      "rcost": 0,
      "att": 3,
      "def": 2,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": 2,
      "str_trait3": 0,
      "str_desc": 25,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "003511032312025C"
    },
    {
      "key": 36,
      "name": "Troll R",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "Lifesteal",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 1,
      "rcost": 1,
      "att": 1,
      "def": 4,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": "B",
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "L",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "0036011143EB000L"
    },
    {
      "key": 37,
      "name": "Shield R",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 1,
      "rcost": 1,
      "att": 1,
      "def": 5,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "E",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "0037011153E0000E"
    },
    {
      "key": 38,
      "name": "Mid drawer",
      "type": "Machine",
      "description": "Draw 1",
      "trait1": "Battlecry",
      "trait2": "Draw",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 3,
      "def": 3,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": 9,
      "str_trait3": 0,
      "str_desc": 14,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "003803033319014C"
    },
    {
      "key": 39,
      "name": "Mid recruits",
      "type": "Machine",
      "description": "Recruit 1 Machine with < 1 attack",
      "trait1": "Battlecry",
      "trait2": "Recruit",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 3,
      "def": 2,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "C",
      "str_trait3": 0,
      "str_desc": "3F",
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "00390303231C03FC"
    },
    {
      "key": 40,
      "name": "Big Kicksy",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 5,
      "def": 2,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "004004052300000C"
    },
    {
      "key": 41,
      "name": "Big Punchy",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 5,
      "def": 3,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "004104053300000C"
    },
    {
      "key": 42,
      "name": "Big Rounded",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 4,
      "def": 4,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "004204044300000C"
    },
    {
      "key": 43,
      "name": "Big Rounded2",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 4,
      "def": 4,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "004304044300000C"
    },
    {
      "key": 44,
      "name": "Big Survivor",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 2,
      "def": 7,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "004404027300000C"
    },
    {
      "key": 45,
      "name": "Big recruits",
      "type": "Machine",
      "description": "Recruit 1 Machine with < 1 attack",
      "trait1": "Battlecry",
      "trait2": "Recruit",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 3,
      "def": 2,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "C",
      "str_trait3": 0,
      "str_desc": "3F",
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "00450403231C03FC"
    },
    {
      "key": 46,
      "name": "Big puller",
      "type": "Machine",
      "description": "Draw 1 Augment from deck",
      "trait1": "Draw",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 1,
      "att": 3,
      "def": 2,
      "str_type": 3,
      "str_trait1": 9,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 15,
      "rarity": "L",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "004602132390015L"
    },
    {
      "key": 47,
      "name": "Big Aggro",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 6,
      "def": 2,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "004704062300000C"
    },
    {
      "key": 48,
      "name": "Huge Punchy",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 6,
      "def": 3,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "004804063300000C"
    },
    {
      "key": 49,
      "name": "Huge Rounded",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 5,
      "def": 5,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "004904055300000C"
    },
    {
      "key": 50,
      "name": "Huge Vamp",
      "type": "Machine",
      "description": "",
      "trait1": "Lifesteal",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 6,
      "def": 2,
      "str_type": 3,
      "str_trait1": "B",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "E",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "0050040623B0000E"
    },
    {
      "key": 51,
      "name": "Huge Shield",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 2,
      "def": 6,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "E",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "0051040263E0000E"
    },
    {
      "key": 52,
      "name": "Huge Kicksy",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 6,
      "def": 3,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "R",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "005204063300000R"
    },
    {
      "key": 53,
      "name": "Huge Blocksy",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 4,
      "def": 5,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "E",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "0053040453E0000E"
    },
    {
      "key": 54,
      "name": "Huge Aggro",
      "type": "Machine",
      "description": "",
      "trait1": "Charge",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 5,
      "def": 4,
      "str_type": 3,
      "str_trait1": 4,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "R",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "005404054340000R"
    },
    {
      "key": 55,
      "name": "Huge Survivor",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 3,
      "def": 6,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "005504036300000C"
    },
    {
      "key": 56,
      "name": "Huge Rush",
      "type": "Machine",
      "description": "",
      "trait1": "Charge",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 6,
      "def": 2,
      "str_type": 3,
      "str_trait1": 4,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "L",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "005604062340000L"
    },
    {
      "key": 57,
      "name": "Huge Draw",
      "type": "Machine",
      "description": "Draw 1",
      "trait1": "Battlecry",
      "trait2": "Draw",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 4,
      "def": 4,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": 9,
      "str_trait3": 0,
      "str_desc": 14,
      "rarity": "R",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "005704044319014R"
    },
    {
      "key": 58,
      "name": "Huge Damage",
      "type": "Machine",
      "description": "Deal 2 Damage",
      "trait1": "Battlecry",
      "trait2": "Damage",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 4,
      "def": 2,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": 5,
      "str_trait3": 0,
      "str_desc": 6,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "005804042315006C"
    },
    {
      "key": 59,
      "name": "Huge Cryhealer",
      "type": "Machine",
      "description": "Heal 3 on 1 random target",
      "trait1": "Battlecry",
      "trait2": "Heal",
      "trait3": "",
      "typenum": 1,
      "lcost": 1,
      "mcost": 2,
      "rcost": 0,
      "att": 5,
      "def": 3,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "A",
      "str_trait3": 0,
      "str_desc": "3A",
      "rarity": "R",
      "total_cost": 4,
      "multiplier": "",
      "total_value": "",
      "string": "00591205331A03AR"
    },
    {
      "key": 60,
      "name": "Huge Healer",
      "type": "Machine",
      "description": "Heal 2",
      "trait1": "Battlecry",
      "trait2": "Heal",
      "trait3": "Taunt",
      "typenum": 1,
      "lcost": 0,
      "mcost": 0,
      "rcost": 2,
      "att": 0,
      "def": 5,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "A",
      "str_trait3": "E",
      "str_desc": 36,
      "rarity": "L",
      "total_cost": 4,
      "multiplier": "",
      "total_value": "",
      "string": "00600020531AE36L"
    },
    {
      "key": 61,
      "name": "Huge Rattle",
      "type": "Machine",
      "description": "Deal 1 Damage to 1 random target",
      "trait1": "Deathrattle",
      "trait2": "Damage",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 5,
      "def": 4,
      "str_type": 3,
      "str_trait1": 6,
      "str_trait2": 5,
      "str_trait3": 0,
      "str_desc": 4,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "006104054365004C"
    },
    {
      "key": 62,
      "name": "Puller5",
      "type": "Machine",
      "description": "Draw 1 Augment from deck",
      "trait1": "Battlecry",
      "trait2": "Draw",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 5,
      "rcost": 0,
      "att": 4,
      "def": 4,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": 9,
      "str_trait3": 0,
      "str_desc": 15,
      "rarity": "E",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "006205044319015E"
    },
    {
      "key": 63,
      "name": "Kicksy5",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 5,
      "rcost": 0,
      "att": 6,
      "def": 2,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "006305062300000C"
    },
    {
      "key": 64,
      "name": "Punchy5",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 5,
      "rcost": 0,
      "att": 6,
      "def": 3,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "006405063300000C"
    },
    {
      "key": 65,
      "name": "Rounded5",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 5,
      "rcost": 0,
      "att": 5,
      "def": 5,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "006505055300000C"
    },
    {
      "key": 66,
      "name": "Vamp5",
      "type": "Machine",
      "description": "",
      "trait1": "Lifesteal",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 5,
      "rcost": 0,
      "att": 6,
      "def": 2,
      "str_type": 3,
      "str_trait1": "B",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "E",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "0066050623B0000E"
    },
    {
      "key": 67,
      "name": "Shield5",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 5,
      "rcost": 0,
      "att": 2,
      "def": 6,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "E",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "0067050263E0000E"
    },
    {
      "key": 68,
      "name": "Drawer5",
      "type": "Machine",
      "description": "Recruit 1 Machine with < 2 attack",
      "trait1": "Battlecry",
      "trait2": "Recruit",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 5,
      "rcost": 0,
      "att": 4,
      "def": 3,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "C",
      "str_trait3": 0,
      "str_desc": 40,
      "rarity": "C",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "00680504331C040C"
    },
    {
      "key": 69,
      "name": "Damage5",
      "type": "Machine",
      "description": "Deal 3 Damage",
      "trait1": "Battlecry",
      "trait2": "Damage",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 5,
      "rcost": 0,
      "att": 5,
      "def": 3,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": 5,
      "str_trait3": 0,
      "str_desc": 9,
      "rarity": "C",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "006905053315009C"
    },
    {
      "key": 70,
      "name": "DeathrattleDmg",
      "type": "Machine",
      "description": "Deal 2 Damage to 1 random target",
      "trait1": "Deathrattle",
      "trait2": "Damage",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 5,
      "rcost": 0,
      "att": 6,
      "def": 3,
      "str_type": 3,
      "str_trait1": 6,
      "str_trait2": 5,
      "str_trait3": 0,
      "str_desc": 8,
      "rarity": "C",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "007005063365008C"
    },
    {
      "key": 71,
      "name": "Charge5",
      "type": "Machine",
      "description": "",
      "trait1": "Charge",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 5,
      "rcost": 0,
      "att": 5,
      "def": 2,
      "str_type": 3,
      "str_trait1": 4,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "R",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "007105052340000R"
    },
    {
      "key": 72,
      "name": "Puller6",
      "type": "Machine",
      "description": "Deal 2 Damage to 1 random target",
      "trait1": "Battlecry",
      "trait2": "Damage",
      "trait3": "",
      "typenum": 1,
      "lcost": 2,
      "mcost": 2,
      "rcost": 0,
      "att": 5,
      "def": 4,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": 5,
      "str_trait3": 0,
      "str_desc": 8,
      "rarity": "C",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "007222054315008C"
    },
    {
      "key": 73,
      "name": "Kicksy6y",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 6,
      "rcost": 0,
      "att": 6,
      "def": 3,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "R",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "007306063300000R"
    },
    {
      "key": 74,
      "name": "Blocksy6",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 6,
      "rcost": 0,
      "att": 4,
      "def": 5,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "E",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "0074060453E0000E"
    },
    {
      "key": 75,
      "name": "Aggro6",
      "type": "Machine",
      "description": "",
      "trait1": "Charge",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 6,
      "rcost": 0,
      "att": 5,
      "def": 4,
      "str_type": 3,
      "str_trait1": 4,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "007506054340000C"
    },
    {
      "key": 76,
      "name": "Survivor6",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 6,
      "rcost": 0,
      "att": 3,
      "def": 6,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "007606036300000C"
    },
    {
      "key": 77,
      "name": "Rush6",
      "type": "Machine",
      "description": "",
      "trait1": "Charge",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 6,
      "rcost": 0,
      "att": 6,
      "def": 2,
      "str_type": 3,
      "str_trait1": 4,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "L",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "007706062340000L"
    },
    {
      "key": 78,
      "name": "RPuller6",
      "type": "Machine",
      "description": "Draw 1 Machine with =< 3 attack",
      "trait1": "Battlecry",
      "trait2": "Recruit",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 2,
      "rcost": 2,
      "att": 4,
      "def": 5,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "C",
      "str_trait3": 0,
      "str_desc": "1A",
      "rarity": "C",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "00780224531C01AC"
    },
    {
      "key": 79,
      "name": "LPuller6",
      "type": "Machine",
      "description": "Recruit 1 Machine with < 2 defense",
      "trait1": "Battlecry",
      "trait2": "Recruit",
      "trait3": "",
      "typenum": 1,
      "lcost": 2,
      "mcost": 2,
      "rcost": 0,
      "att": 4,
      "def": 2,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "C",
      "str_trait3": 0,
      "str_desc": 41,
      "rarity": "C",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "00792204231C041C"
    },
    {
      "key": 80,
      "name": "Deathrattle6",
      "type": "Machine",
      "description": "Draw 1 Machine with < 2 attack",
      "trait1": "Battlecry",
      "trait2": "Recruit",
      "trait3": "",
      "typenum": 1,
      "lcost": 1,
      "mcost": 2,
      "rcost": 1,
      "att": 4,
      "def": 4,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "C",
      "str_trait3": 0,
      "str_desc": 18,
      "rarity": "C",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "00801214431C018C"
    },
    {
      "key": 81,
      "name": "En. Round",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 1,
      "mcost": 3,
      "rcost": 1,
      "att": 6,
      "def": 4,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "R",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "008113164300000R"
    },
    {
      "key": 82,
      "name": "En. Aggro",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 2,
      "mcost": 3,
      "rcost": 0,
      "att": 6,
      "def": 2,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "R",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "008223062300000R"
    },
    {
      "key": 83,
      "name": "En. Shield",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 3,
      "rcost": 2,
      "att": 4,
      "def": 6,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "R",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "0083032463E0000R"
    },
    {
      "key": 84,
      "name": "En. Charger",
      "type": "Machine",
      "description": "",
      "trait1": "Charge",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 1,
      "mcost": 4,
      "rcost": 0,
      "att": 6,
      "def": 3,
      "str_type": 3,
      "str_trait1": 4,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "L",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "008414063340000L"
    },
    {
      "key": 85,
      "name": "En. Taunt",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 4,
      "rcost": 1,
      "att": 3,
      "def": 6,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "E",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "0085041363E0000E"
    },
    {
      "key": 86,
      "name": "En. RoundN",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 7,
      "rcost": 0,
      "att": 7,
      "def": 7,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "E",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "008607077300000E"
    },
    {
      "key": 87,
      "name": "Punchy X",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 7,
      "rcost": 0,
      "att": 8,
      "def": 6,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "E",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "008707086300000E"
    },
    {
      "key": 88,
      "name": "Blocksy X",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 7,
      "rcost": 0,
      "att": 6,
      "def": 8,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "R",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "008807068300000R"
    },
    {
      "key": 89,
      "name": "Survivor X",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 7,
      "rcost": 0,
      "att": 3,
      "def": 9,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "0089070393E0000C"
    },
    {
      "key": 90,
      "name": "RattlerRec X",
      "type": "Machine",
      "description": "Draw 1 Machine with < 3 attack",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 3,
      "rcost": 2,
      "att": 6,
      "def": 4,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 19,
      "rarity": "E",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "009003264300019E"
    },
    {
      "key": 91,
      "name": "CryHealer X",
      "type": "Machine",
      "description": "Heal 6",
      "trait1": "Battlecry",
      "trait2": "Heal",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 3,
      "rcost": 2,
      "att": 6,
      "def": 4,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "A",
      "str_trait3": 0,
      "str_desc": "3B",
      "rarity": "R",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "00910326431A03BR"
    },
    {
      "key": 92,
      "name": "Big Bertha",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 7,
      "rcost": 0,
      "att": 7,
      "def": 7,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "C",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "009207077300000C"
    },
    {
      "key": 93,
      "name": "RattleDmg X",
      "type": "Machine",
      "description": "Deal 4 Damage to 1 random target",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 7,
      "rcost": 0,
      "att": 8,
      "def": 4,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "0E",
      "rarity": "R",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "00930708430000ER"
    },
    {
      "key": 94,
      "name": "Rrecruiter X",
      "type": "Machine",
      "description": "Recruit 1 Machine with < 4 attack",
      "trait1": "Battlecry",
      "trait2": "Recruit",
      "trait3": "",
      "typenum": 1,
      "lcost": 2,
      "mcost": 3,
      "rcost": 0,
      "att": 5,
      "def": 4,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "C",
      "str_trait3": 0,
      "str_desc": "3E",
      "rarity": "E",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "00942305431C03EE"
    },
    {
      "key": 95,
      "name": "Lrecruiter X",
      "type": "Machine",
      "description": [
        "Draw 2 cards",
        "Discard 1"
      ],
      "trait1": "Battlecry",
      "trait2": "Draw",
      "trait3": "Discard",
      "typenum": 1,
      "lcost": 0,
      "mcost": 3,
      "rcost": 2,
      "att": 3,
      "def": 6,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": 9,
      "str_trait3": 8,
      "str_desc": "1B",
      "rarity": "E",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "00950323631981BE"
    },
    {
      "key": 96,
      "name": "Kicksy X",
      "type": "Machine",
      "description": "",
      "trait1": "",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 7,
      "rcost": 0,
      "att": 9,
      "def": 4,
      "str_type": 3,
      "str_trait1": 0,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "R",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "009607094300000R"
    },
    {
      "key": 97,
      "name": "BuildingBlocks",
      "type": "Machine",
      "description": "Heal 2 on 1 Building",
      "trait1": "Battlecry",
      "trait2": "Heal",
      "trait3": "",
      "typenum": 1,
      "lcost": 0,
      "mcost": 7,
      "rcost": 0,
      "att": 6,
      "def": 8,
      "str_type": 3,
      "str_trait1": 1,
      "str_trait2": "A",
      "str_trait3": 0,
      "str_desc": "3D",
      "rarity": "R",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "00970706831A03DR"
    },
    {
      "key": 98,
      "name": "Charger X",
      "type": "Machine",
      "description": "",
      "trait1": "Charge",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 1,
      "mcost": 7,
      "rcost": 0,
      "att": 7,
      "def": 3,
      "str_type": 3,
      "str_trait1": 4,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "E",
      "total_cost": 9,
      "multiplier": 1,
      "total_value": "",
      "string": "009817073340000E"
    },
    {
      "key": 99,
      "name": "Wally",
      "type": "Machine",
      "description": "",
      "trait1": "Taunt",
      "trait2": "",
      "trait3": "",
      "typenum": 1,
      "lcost": 2,
      "mcost": 0,
      "rcost": 2,
      "att": 3,
      "def": 9,
      "str_type": 3,
      "str_trait1": "E",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 0,
      "rarity": "L",
      "total_cost": 8,
      "multiplier": 1,
      "total_value": "",
      "string": "0099202393E0000L"
    },
    {
      "key": 100,
      "name": "Super Duper",
      "type": "Machine",
      "description": "Recruit 1 copy of this Machine",
      "trait1": "Lifesteal",
      "trait2": "Recruit",
      "trait3": "",
      "typenum": 1,
      "lcost": 2,
      "mcost": 0,
      "rcost": 2,
      "att": 4,
      "def": 3,
      "str_type": 3,
      "str_trait1": "B",
      "str_trait2": "C",
      "str_trait3": 0,
      "str_desc": 44,
      "rarity": "L",
      "total_cost": 8,
      "multiplier": 2,
      "total_value": "",
      "string": "0100202433BC044L"
    },
    {
      "key": 101,
      "name": "Damage wave",
      "type": "Augment",
      "description": "Deal 1 Damage to all Machines",
      "trait1": "Damage",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 5,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 5,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "010102000250005C"
    },
    {
      "key": 102,
      "name": "Bombing Run",
      "type": "Augment",
      "description": "Deal 3 Damage to all Machines",
      "trait1": "Damage",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 5,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "0B",
      "rarity": "R",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "01020400025000BR"
    },
    {
      "key": 103,
      "name": "Mechanic",
      "type": "Augment",
      "description": "Reduce 1 random Machine summon mcost by half",
      "trait1": "Reduce",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": "C",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 45,
      "rarity": "L",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "0103030002C0045L"
    },
    {
      "key": 104,
      "name": "Double Down",
      "type": "Augment",
      "description": "Destroy 2 random Machines",
      "trait1": "Destroy",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 4,
      "rcost": 1,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 7,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 13,
      "rarity": "R",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "010404100270013R"
    },
    {
      "key": 105,
      "name": "EMP",
      "type": "Augment",
      "description": "Destroy all Machines",
      "trait1": "Destroy",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 4,
      "rcost": 1,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 7,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 11,
      "rarity": "E",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "010504100270011E"
    },
    {
      "key": 106,
      "name": "Tune-Up",
      "type": "Augment",
      "description": "Heal 1 Def for your Machines",
      "trait1": "Heal",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": "A",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 34,
      "rarity": "R",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "0106020002A0034R"
    },
    {
      "key": 107,
      "name": "Healing Run",
      "type": "Augment",
      "description": "Heal 3 Def for all Machines",
      "trait1": "Heal",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 1,
      "mcost": 4,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": "A",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 39,
      "rarity": "C",
      "total_cost": 6,
      "multiplier": 1,
      "total_value": "",
      "string": "0107140002A0039C"
    },
    {
      "key": 108,
      "name": "Tech Upgrade",
      "type": "Augment",
      "description": "Heal 1 Def for all Machines",
      "trait1": "Heal",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 1,
      "mcost": 1,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": "A",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 33,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "0108110002A0033C"
    },
    {
      "key": 109,
      "name": "L Buff 3cost",
      "type": "Augment",
      "description": [
        "Give 1 Machine +1/+0",
        "Draw 1"
      ],
      "trait1": "Buff",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 1,
      "mcost": 1,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 2,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 26,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "010911000220026C"
    },
    {
      "key": 110,
      "name": "L Buff 5cost",
      "type": "Augment",
      "description": "Give 1 Machine +2/+0",
      "trait1": "Buff",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 1,
      "mcost": 2,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 2,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 29,
      "rarity": "R",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "011012000220029R"
    },
    {
      "key": 111,
      "name": "L Board 5cost",
      "type": "Augment",
      "description": "Give your Machines in 1 Lane +2/+2 for the Turn",
      "trait1": "BuffAll",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 2,
      "mcost": 1,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 3,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 31,
      "rarity": "E",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "011121000230031E"
    },
    {
      "key": 112,
      "name": "Overclocked",
      "type": "Augment",
      "description": "Give 1 Machine 'Charge'",
      "trait1": "Buff",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 2,
      "mcost": 0,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 2,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "2D",
      "rarity": "E",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "01122000022002DE"
    },
    {
      "key": 113,
      "name": "Magnetic",
      "type": "Augment",
      "description": "Give 1 Machine 'Taunt'",
      "trait1": "Buff",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 0,
      "rcost": 2,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 2,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "2E",
      "rarity": "E",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "01130020022002EE"
    },
    {
      "key": 114,
      "name": "R Buff 3 Cost",
      "type": "Augment",
      "description": [
        "Give 1 Machine +0/+1",
        "Draw 1"
      ],
      "trait1": "Buff",
      "trait2": "Draw",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 1,
      "rcost": 1,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 2,
      "str_trait2": 9,
      "str_trait3": 0,
      "str_desc": 24,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "011401100229024C"
    },
    {
      "key": 115,
      "name": "R Buff 5 Cost",
      "type": "Augment",
      "description": "Give 1 Machine +1/+2",
      "trait1": "Buff",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 2,
      "rcost": 1,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 2,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 28,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "011502100220028C"
    },
    {
      "key": 116,
      "name": "R Buff 2 Cost",
      "type": "Augment",
      "description": "Give 1 Machine +0/+1",
      "trait1": "Buff",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 2,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 23,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "011602000220023C"
    },
    {
      "key": 117,
      "name": "Upgrades",
      "type": "Augment",
      "description": "Give all Machines in Lane +1/+1",
      "trait1": "BuffAll",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 1,
      "mcost": 1,
      "rcost": 1,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 3,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 30,
      "rarity": "E",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "011711100230030E"
    },
    {
      "key": 118,
      "name": "DU Lift",
      "type": "Augment",
      "description": "Give 1 Machine +1/+1",
      "trait1": "Buff",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 2,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 27,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "011802000220027C"
    },
    {
      "key": 119,
      "name": "4K Lift",
      "type": "Augment",
      "description": "Give 1 Machine +4/+4",
      "trait1": "Buff",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 1,
      "mcost": 3,
      "rcost": 1,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 2,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "2B",
      "rarity": "L",
      "total_cost": 7,
      "multiplier": 1,
      "total_value": "",
      "string": "01191310022002BL"
    },
    {
      "key": 120,
      "name": "Overdrive",
      "type": "Augment",
      "description": "Give 1 Machine +3/+0",
      "trait1": "Buff",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 2,
      "str_trait2": 7,
      "str_trait3": 0,
      "str_desc": "2A",
      "rarity": "E",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "01200300022702AE"
    },
    {
      "key": 121,
      "name": "Rust",
      "type": "Augment",
      "description": "Give 1 Machine -2/+0",
      "trait1": "Buff",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 2,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "2C",
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "01210300022002CC"
    },
    {
      "key": 122,
      "name": "Draw 2",
      "type": "Augment",
      "description": "Draw 2",
      "trait1": "Draw",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 9,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "1B",
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "01220300029001BC"
    },
    {
      "key": 123,
      "name": "Draw 3",
      "type": "Augment",
      "description": "Draw 3",
      "trait1": "Draw",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 1,
      "mcost": 1,
      "rcost": 1,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 9,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "1E",
      "rarity": "R",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "01231110029001ER"
    },
    {
      "key": 124,
      "name": "DrawDiscard",
      "type": "Augment",
      "description": [
        "Draw 2",
        "Discard 1"
      ],
      "trait1": "Draw",
      "trait2": "Discard",
      "trait3": "",
      "typenum": 2,
      "lcost": 1,
      "mcost": 0,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 9,
      "str_trait2": 8,
      "str_trait3": 0,
      "str_desc": "1D",
      "rarity": "E",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "01241000029801DE"
    },
    {
      "key": 125,
      "name": "Damage22",
      "type": "Augment",
      "description": "Deal 2 Damage to 2 random Machines",
      "trait1": "Damage",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 1,
      "mcost": 0,
      "rcost": 1,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 5,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 7,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "012510100250007C"
    },
    {
      "key": 126,
      "name": "Last Resort",
      "type": "Augment",
      "description": "Take no Damage until your next Turn",
      "trait1": "Immune",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": "A",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 49,
      "rarity": "E",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "0126030002A0049E"
    },
    {
      "key": 127,
      "name": "HealAny1",
      "type": "Augment",
      "description": "Heal 3 Def",
      "trait1": "Heal",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": "A",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 38,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "0127020002A0038C"
    },
    {
      "key": 128,
      "name": "HealAny2",
      "type": "Augment",
      "description": "Heal 4 Def",
      "trait1": "Heal",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": "A",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "3B",
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "0128030002A003BC"
    },
    {
      "key": 129,
      "name": "DmgAny1",
      "type": "Augment",
      "description": "Deal 3 Damage",
      "trait1": "Damage",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 3,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 5,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 9,
      "rarity": "C",
      "total_cost": 3,
      "multiplier": 1,
      "total_value": "",
      "string": "012903000250009C"
    },
    {
      "key": 130,
      "name": "DmgAny2",
      "type": "Augment",
      "description": "Deal 4 Damage",
      "trait1": "Damage",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 5,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 5,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "0D",
      "rarity": "C",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "01300500025000DC"
    },
    {
      "key": 131,
      "name": "DmgRand1",
      "type": "Augment",
      "description": "Deal 1 Damage to 3 random Machines",
      "trait1": "Damage",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 1,
      "mcost": 0,
      "rcost": 1,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 5,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 3,
      "rarity": "R",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "013110100250003R"
    },
    {
      "key": 132,
      "name": "Recruit",
      "type": "Augment",
      "description": "Recruit 2 < 4 mcost Machine",
      "trait1": "Recruit",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 2,
      "mcost": 0,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": "C",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 43,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "0132200002C0043C"
    },
    {
      "key": 133,
      "name": "RecruitL",
      "type": "Augment",
      "description": "Recruit 1 Machine with Taunt",
      "trait1": "Recruit",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 0,
      "rcost": 2,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": "C",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 42,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "0133002002C0042C"
    },
    {
      "key": 134,
      "name": "ReviveRandAny",
      "type": "Augment",
      "description": "Revive 1 random Machine",
      "trait1": "Revive",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 5,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": "D",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 48,
      "rarity": "E",
      "total_cost": 5,
      "multiplier": 1,
      "total_value": "",
      "string": "0134050002D0048E"
    },
    {
      "key": 135,
      "name": "ReviveRandOwn",
      "type": "Augment",
      "description": "Revive 1 random Machine",
      "trait1": "Revive",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 4,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": "D",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 47,
      "rarity": "E",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "0135040002D0047E"
    },
    {
      "key": 136,
      "name": "Draw3Discard1",
      "type": "Augment",
      "description": [
        "Draw 3",
        "Discard 1"
      ],
      "trait1": "Draw",
      "trait2": "Discard",
      "trait3": "",
      "typenum": 2,
      "lcost": 1,
      "mcost": 0,
      "rcost": 1,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 9,
      "str_trait2": 8,
      "str_trait3": 0,
      "str_desc": 20,
      "rarity": "R",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "013610100298020R"
    },
    {
      "key": 137,
      "name": "Meltdown",
      "type": "Augment",
      "description": "Deal 3 Damage to all Machines in Lane",
      "trait1": "Damage",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 2,
      "mcost": 0,
      "rcost": 2,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 5,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "0C",
      "rarity": "R",
      "total_cost": 8,
      "multiplier": 1,
      "total_value": "",
      "string": "01372020025000CR"
    },
    {
      "key": 138,
      "name": "Demolition",
      "type": "Augment",
      "description": "Destroy 1 Building",
      "trait1": "Destroy",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 2,
      "mcost": 0,
      "rcost": 2,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 7,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 10,
      "rarity": "E",
      "total_cost": 8,
      "multiplier": 1,
      "total_value": "",
      "string": "013820200270010E"
    },
    {
      "key": 139,
      "name": "Downfall",
      "type": "Augment",
      "description": "Destroy 1 random Machine in this Lane",
      "trait1": "Destroy",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 1,
      "mcost": 0,
      "rcost": 1,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 7,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 12,
      "rarity": "R",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "013910100270012R"
    },
    {
      "key": 140,
      "name": "Earthquake",
      "type": "Augment",
      "description": "Deal 5 Damage to all",
      "trait1": "Damage",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 2,
      "mcost": 2,
      "rcost": 2,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 5,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "0F",
      "rarity": "R",
      "total_cost": 10,
      "multiplier": 1,
      "total_value": "",
      "string": "01402220025000FR"
    },
    {
      "key": 141,
      "name": "Thicc Walls",
      "type": "Augment",
      "description": "Give 1 Building +0/+2",
      "trait1": "Buff",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 2,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 22,
      "rarity": "C",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "014102000220022C"
    },
    {
      "key": 142,
      "name": "Sabotage",
      "type": "Augment",
      "description": "Deal 3 Damage to 1 Building",
      "trait1": "Damage",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 5,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "0A",
      "rarity": "L",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "01420200025000AL"
    },
    {
      "key": 143,
      "name": "PullBuilding",
      "type": "Augment",
      "description": "Draw 1 Building",
      "trait1": "Draw",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 0,
      "mcost": 0,
      "rcost": 2,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 9,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 21,
      "rarity": "E",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "014300200290021E"
    },
    {
      "key": 144,
      "name": "PullMachines",
      "type": "Augment",
      "description": "Draw 2 Machines",
      "trait1": "Draw",
      "trait2": "",
      "trait3": "",
      "typenum": 2,
      "lcost": 2,
      "mcost": 0,
      "rcost": 0,
      "att": 0,
      "def": 0,
      "str_type": 2,
      "str_trait1": 9,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": "1D",
      "rarity": "E",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "01442000029001DE"
    },
    {
      "key": 145,
      "name": "Artillery",
      "type": "Building",
      "description": "Deal 1 Damage in this Lane",
      "trait1": "Damage",
      "trait2": "",
      "trait3": "",
      "typenum": 3,
      "lcost": 1,
      "mcost": 0,
      "rcost": 1,
      "att": 0,
      "def": 4,
      "str_type": 3,
      "str_trait1": 5,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 2,
      "rarity": "E",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "014510104350002E"
    },
    {
      "key": 146,
      "name": "Turtle",
      "type": "Building",
      "description": "Heal 1 Def per Turn in this Lane",
      "trait1": "Heal",
      "trait2": "",
      "trait3": "",
      "typenum": 3,
      "lcost": 0,
      "mcost": 2,
      "rcost": 0,
      "att": 0,
      "def": 4,
      "str_type": 3,
      "str_trait1": "A",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 32,
      "rarity": "E",
      "total_cost": 2,
      "multiplier": 1,
      "total_value": "",
      "string": "0146020043A0032E"
    },
    {
      "key": 147,
      "name": "Workshop",
      "type": "Building",
      "description": "Heal 1 Machine 1 Def per Turn in this Lane",
      "trait1": "Heal",
      "trait2": "",
      "trait3": "",
      "typenum": 3,
      "lcost": 1,
      "mcost": 2,
      "rcost": 0,
      "att": 0,
      "def": 8,
      "str_type": 3,
      "str_trait1": "A",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 35,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "0147120083A0035C"
    },
    {
      "key": 148,
      "name": "Overcharger",
      "type": "Building",
      "description": "Give +1/+0 for 1 Machine this Turn in this Lane",
      "trait1": "Buff",
      "trait2": "",
      "trait3": "",
      "typenum": 3,
      "lcost": 0,
      "mcost": 2,
      "rcost": 1,
      "att": 0,
      "def": 8,
      "str_type": 3,
      "str_trait1": 2,
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 1,
      "rarity": "C",
      "total_cost": 4,
      "multiplier": 1,
      "total_value": "",
      "string": "014802108320001C"
    },
    {
      "key": 149,
      "name": "Power Plant",
      "type": "Building",
      "description": "Reduce summon costs in this Lane by 1",
      "trait1": "Reduce",
      "trait2": "",
      "trait3": "",
      "typenum": 3,
      "lcost": 0,
      "mcost": 4,
      "rcost": 2,
      "att": 0,
      "def": 5,
      "str_type": 3,
      "str_trait1": "C",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 46,
      "rarity": "L",
      "total_cost": 8,
      "multiplier": 1,
      "total_value": "",
      "string": "0149042053C0046L"
    },
    {
      "key": 150,
      "name": "War Factory",
      "type": "Building",
      "description": "Reduce summon mcosts in this Lane by 1",
      "trait1": "Reduce",
      "trait2": "",
      "trait3": "",
      "typenum": 3,
      "lcost": 2,
      "mcost": 4,
      "rcost": 0,
      "att": 0,
      "def": 5,
      "str_type": 3,
      "str_trait1": "C",
      "str_trait2": 0,
      "str_trait3": 0,
      "str_desc": 46,
      "rarity": "L",
      "total_cost": 8,
      "multiplier": 1,
      "total_value": "",
      "string": "0150240053C0046L"
    }
  ]
}